export const ADD_NEW_SERVER = 'ADD_NEW_SERVER';
export const REMOVE_NEW_SERVER = 'REMOVE_NEW_SERVER';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';
export const GET_SERVER_LIST = 'GET_SERVER_LIST';

